
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8414:8414"
    environment:
      - PORT=8414
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8414/health"]
      timeout: 5s
      interval: 30s
      retries: 3
      start_period: 40s
