version: '3.8'

services:
  app:
    build: .
    ports:
      - "8414:8414"
    environment:
      - PORT=8414
      # Use the transaction pooler connection string directly
      - DSN_DB=postgresql://postgres.bekzvtigeedgzuuszovj:balakotalu77@aws-0-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require
    env_file:
      - .env
    restart: unless-stopped
    # Use host networking to avoid Docker network issues
    network_mode: "host"
    # Alternative: use bridge with extra_hosts
    # network_mode: "bridge"
    # extra_hosts:
    #   - "aws-0-ap-south-1.pooler.supabase.com:host-gateway"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8414/health"]
      timeout: 10s
      interval: 30s
      retries: 5
      start_period: 60s
